apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: srs-fleet-manager-uda7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: srs-fleet-manager-uda7
    app.kubernetes.io/part-of: srs-fleet-manager
  name: srs-fleet-manager-uda7
  namespace: nipatil-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: srs-fleet-manager-uda7
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: srs-fleet-manager-uda7
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:7580cb3bb0721b5d02c511959b494fb3ed470b8c6a20507bb1c888aed170de20
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
